# Generated by Django 3.0.5 on 2020-04-16 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 18, 43, 30, 49068), verbose_name='date published'),
        ),
    ]
